/* WATCOM Interface Generator   Version 1.0 */
/* This file is generated by PowerBuilder.
 * Do not modify this file.
 * This file contains interface code called by PowerBuilder.
 */ 

#include <pbdll.h>

#include "u_cpp_LO.hpp"

extern "C" {
short PB_EXPORT u_cpp_getfontinfuf_init( u_cpp_getfontinf *this_hdl, long al_hwnd );
unsigned short PB_EXPORT u_cpp_getfontinfuf_getfontcount( u_cpp_getfontinf *this_hdl );
short PB_EXPORT u_cpp_getfontinfuf_getfontname( u_cpp_getfontinf *this_hdl, char *as_fontname, short ai_fontnum );
u_cpp_getfontinf *PB_EXPORT u_cpp_getfontinf_CPP_CONSTRUCTOR();
void PB_EXPORT u_cpp_getfontinf_CPP_DESTRUCTOR( u_cpp_getfontinf *this_hdl );
}

short PB_EXPORT u_cpp_getfontinfuf_init( u_cpp_getfontinf *this_hdl, long al_hwnd ) {
    return( this_hdl->uf_init( al_hwnd ) );
}

unsigned short PB_EXPORT u_cpp_getfontinfuf_getfontcount( u_cpp_getfontinf *this_hdl ) {
    return( this_hdl->uf_getfontcount(  ) );
}

short PB_EXPORT u_cpp_getfontinfuf_getfontname( u_cpp_getfontinf *this_hdl, char *as_fontname, short ai_fontnum ) {
    return( this_hdl->uf_getfontname( as_fontname, ai_fontnum ) );
}

u_cpp_getfontinf *PB_EXPORT u_cpp_getfontinf_CPP_CONSTRUCTOR() {
    return( new u_cpp_getfontinf );
}

void PB_EXPORT u_cpp_getfontinf_CPP_DESTRUCTOR( u_cpp_getfontinf *this_hdl ) {
    delete this_hdl;
}

