/* This file is generated by PowerBuilder.
 * You may modify it in any way you wish but do not remove
 * Libmain and WEP.  Without them you will be unable to link your DLL.
 */ 

#include <windows.h>
#include "pbdll.h"

#ifdef __NT__

extern "C" {

int __stdcall DLLMain( DWORD, DWORD reason, DWORD )
{
    if( reason == DLL_PROCESS_ATTACH ) {
        extern char __WD_Present;
        if( __WD_Present ) { // this is a hook for the Watcom debugger.
            extern void Int3WithSignature( char __far * );
            #pragma aux Int3WithSignature parm caller [] = \
                    "int 3" \
                    "jmp short L1" \
                    'W' 'V' 'I' 'D' 'E' 'O' \
                    "L1:"
            Int3WithSignature( "DLL Loaded" );
        }
    }
    return( 1 );
}

};

#else

int PB_EXPORT LibMain( HANDLE, WORD, WORD, LPSTR )
{
    return( 1 );
}

int PB_EXPORT WEP( int )
{
    return( 1 );
}

#endif // PowerBuilder code, do not remove 
