/* WATCOM Interface Generator   Version 1.0 */
/* This file contains code generated by PowerBuilder.
 * Do not modify code delimited by comments of the form:
 * // $PB$ -- begin generated code for object <>.  Do not modify this code
 * // $PB$ -- end generated code for object <>.
 * This file contains the the C++ class definition for your user object.
 */ 

#include <string.hpp>
#include <windows.h>
#include <commctrl.h>
#include <stdio.h>
#include <stdlib.h>

typedef struct tagTrueTypeFontInfo
{	LOGFONT *plf;
	TEXTMETRIC *ptm;
} TRUETYPEFONTINFO,*PTRUETYPEFONTINFO;


// $PB$ -- begin generated code for object <u_cpp_getfontinf>.  Do not modify this code
class u_cpp_getfontinf {
public:
    virtual short uf_init( long al_hwnd );
    virtual unsigned short uf_getfontcount(  );
    virtual short uf_getfontname( char *as_fontname, short ai_fontnum );
// $PB$ -- end generated code for object <u_cpp_getfontinf>.
public:
    virtual ~u_cpp_getfontinf() {}
    /*
     * PUT YOUR DECLARATIONS HERE
     */

};

int APIENTRY MyEnumfontFacesProc(LPLOGFONT,LPTEXTMETRIC,DWORD,LPINT);
int APIENTRY MyEnumfontCountProc(LPLOGFONT,LPTEXTMETRIC,DWORD,LPINT);
PTRUETYPEFONTINFO BuildFontList(HDC,LPINT);